server:
  port: 8770
  tomcat:
    max-connections: 10000 #default
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://172.16.63.34:8761/eureka}
  instance:
    preferIpAddress: true
#    statusPageUrlPath: ${eureka.hostname}/info
#    healthCheckUrlPath: ${eureka.hostname}/health
    health-check-url:
      enabled: true
feign:
  hystrix:
    enabled: true

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000

spring:
  application:
    name: message_center
  profiles:
    include: redis-aliyun,postgre-aliyun,kafka-aliyun

logging:
  level: info

#自定义参数
isNoteTaker: 1
