server:
  port: 8763
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
#    statusPageUrlPath: ${eureka.hostname}/info
#    healthCheckUrlPath: ${eureka.hostname}/health
    health-check-url:
      enabled: true
spring:
  application:
    name: feign
  profiles:
    active: redis



management:
#  health:
#    mail:
#      enabled: false
  security:
    enabled: true
logging:
  level: debug
