producer:
  reconnect:
    backoff.ms: 2000
  retry:
    backoff.ms: 2000
  connections.max.idle.ms: 540000
  bootstrap.servers: 172.16.20.205:9092
  retries: 30
  key.serializer: org.apache.kafka.common.serialization.StringSerializer
  value.serializer: org.apache.kafka.common.serialization.StringSerializer
  compression.type: gzip
  acks: all #等待所有follower确认
  buffer.memory: 33554432

consumer:
  bootstrap.servers: 172.16.20.205:9092
  session.timeout.ms: 30000
  key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
  value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
  enable.auto.commit: false
  max.poll.records: 1000
  group.id: trade_guide #不同jar包需要修改

