eureka:
 client:
   serviceUrl:
      defaultZone: http://172.16.63.34:8761/eureka/
server:
  port: 8772
spring:
  application:
    name: raven_guide
  profiles:
    include: redis-aliyun,kafka-aliyun