eureka:
  client:
    serviceUrl:
      defaultZone: http://172.16.63.34:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: service-taker
  profiles:
    include: postgre-aliyun, redis-aliyun, kafka-aliyun